### ISSUE TITLE
Move issues from Google sheet over to Github

### ISSUE THREAD

**Issue by LindaKiel** [kpwhri/heartsteps#141]

**Comment by nickdotreid** [comment]
I think I've completed this issue, and I'll close this issue when I go over the existing issues with @klasnja and @LindaKiel 

My guess is that we now have some duplicate issues, which hopefully we can find and remove later.

I didn't include two rows from the bugs sheet:
* **Row 9** which is **row 7** and now issue #149 
* **Row 12** which is actually issue #128
