### ISSUE TITLE
Watch app authentication breaking

### ISSUE THREAD

**Issue by nickdotreid** [kpwhri/heartsteps#149]
We are creating a new watch app authentication process because using the fitbit watch app settings page was a part of the process that participants had difficulty with.

**To Do**
- [x] Create secondary API endpoint for watch-app step counts to be reported.
- [x] Add pin entry screen into HeartSteps app for debugging
- [x] Reported number of step counts from watch app should be totals at times -- or snap shots of watch state
- [x] Server creates step count records based on snap shots of watch state
- [x] Add pin entry screen into onboarding process

----
**Preserved Old Ticket Just Because**

"Nick not sure how to approach. try to reproduce? Don't know why this is happening. There's an update for Versa. Nick and Pedja to check updates, and running out of battery. Where is the token stored (don't think it's this)? 

12/17 Nick: Tried running out of battery, seemed to have no effect.
--> Will test with software update
--> Will add code to track how many unauthorized requests we are getting  
12/18 - still not clear what's happening. Nick can timestamp, but not sure how to approach de-bugging. Look at sever logs? Nick has tried, nothing obviously wrong. Pedja will take a look at the java script code 
12/19. Two people who can't switch over to current watch app 10063 and 10426         
1/9 - not fix yet. Pedja will test this this week. Still trying to figure out."
5/14 - we are going to have new UMich student, Jake, work on rebuild. Continuing to have issues.

**Comment by jkhuangg** [comment]
maybe it's because of stepcounts data exceeding Fitbit buffer limit?
![hs](https://user-images.githubusercontent.com/33791721/88837435-458f0a80-d1a6-11ea-9f78-aa5fcff1bcd8.png)
