### ISSUE TITLE
Documentation for exported data

### ISSUE THREAD

**Issue by pengliao** [kpwhri/heartsteps#168]
**Below is Susan's comments/request about the documentation for exported data**

It is a total hassle to do the following but it will make an enormous difference when people have to do data analyses and they are unable to find you (or you don't want to be bothered all the time).  In machine learning/data analyses it is critical to know if a variable is missing and if so why it is missing.  There are often multiple reasons for why a variable might be missing.  In this case if possible it is good (if you are able) to give the missing variable entries different labels depending on why the variable entry is missing.    It is ok to state that you don't know why a variable entry is NA or missing or NULL. 

1) At the beginning of each file it would be good to have a description of where the data comes from in english that someone like me can understand.   Like for the fitibit_minutes.csv  file it would be good to know if steps always comes from the wrist tracker and not from phone. I would want to know this for all variables in each file.   (usually one file has variables all from same source, e.g. wrist tracker, but just tell me that).

2) Each variable (data column) should have a list of possible values that variable can take.  For example the column "Steps"  has values in {0,1,....} or NA       (actually I am not sure if the entry is labeled Null or NA but it should state that here).  If there are multiple ways for a variable to signal that the data is missing or bad then these should be listed.    If you have any idea about why the variable can take the NA value then this should be stated here. In many settings there are multiple reasons why a variable can be NA.  In other data sets I have seen there are NA's , **, UK and so on and each mean a different kind of thing.   We need to know if this is the case. 

Once we have the above for each file and each  variable then we will start to ask you about peculiar variable combinations (such as why would heart rate is NA, but the step count is zero?   or why would heart rate be NA but step count positive?
I think we can only really look at these variable combinations once 1) and 2) above are done.

**Comment by nickdotreid** [comment]
We have made good progress of this documentation process. I'm closing this ticket so we can focus on more specific tickets.
