### ISSUE TITLE
Missing Record on 2020/6/22

### ISSUE THREAD

**Issue by mengeks** [kpwhri/heartsteps#179]
There is no RECORD (not missing value) at 2020/6/22 for id=10262, at per-minute.csv.

And it is not the end date. The last date in that file was 2020/8/21. 

I have investigate id=10152 whose end date is after 2020/6/22. The same issue appears.

**Comment by klasnja** [comment]
Can you be a little clearer on what this issue is? Are you saying that for
this participant (10262) we have no minute-level data for 6/22 at all, but
that data then picks back up on 6/23? Or are you saying something else?

Thanks,
Pedja

**Comment by mengeks** [comment]
Thanks Pedja for asking. I do mean that,  i.e., at least for participants 10262 and 10152, we have no minute-level data for 6/22 at all, but that data then picks back up on 6/23

**Comment by mengeks** [comment]
@nickdotreid I think during our meeting on 10/2, you mentioned that you've made a fix for this. I just (10/3 2AM PST) went to Goole Buckets, and the csv of 10262 is only updated at 9/26, which means I could not checked whether your fix is there.

Add the screenshot of the issue: This is what happens for 10262 (
![image](https://user-images.githubusercontent.com/12406669/94987700-13d74e80-051d-11eb-8ff4-24d1b71ec3d7.png)

**Comment by jup014** [comment]
@mengeks I'm revisiting all open bugs. Are we still experiencing this issue? How can we help?

**Comment by mengeks** [comment]
This is now fixed. Thanks!
