### ISSUE TITLE
Missing value in treatment probability at "anti-sedentary-decisions.csv"

### ISSUE THREAD

**Issue by mengeks** [kpwhri/heartsteps#189]
@nickdotreid 's conjecture is that this should be an exporting bug that the imputation procedure does not assign any value to 
treatment probability

My initial investigation (on 3 participants) support this view. It indicates that all rows with missing value on treatment probability are those whose data is imputed (whose "imputation" column is 1).

**Comment by mengeks** [comment]
To make it clear, the conjecture says: {rows that has treatment_probability == NA} =   {rows that has imputed == 1}

**Comment by jup014** [comment]
@mengeks I'm revisiting all open bugs. Are we still experiencing this issue? How can we help?

**Comment by mengeks** [comment]
This is not an issue anymore. Feel free to close. Thanks!
