### ISSUE TITLE
Participant.Participant.enrollment_token is too short

### ISSUE THREAD

**Issue by jup014** [kpwhri/heartsteps#203]
The Participant.Participant.enrollment_token column has a length limit of 10 characters.

And it has a universal unique condition. 

https://github.com/kpwhri/heartsteps/blob/4b9c0bfc7e75b26830a50756786b76d8d23b4974/server/participants/models.py#L96

Can we increase it to 20 characters or more?

**Comment by klasnja** [comment]
Jungwan,

This column is for unique entry tokens that are randomly generated. They
have the format of XXXX-XXXX, where Xs are letters, so there a *lot* of
unique combinations that are possible (I’ll leave the calculation of the
exact number as an exercise for the reader). We do not need a longer token
format. Why do you think increasing the length would be useful?

Thanks,
Pedja

**Comment by jup014** [comment]
Hi Pedja,


Oh, is it randomly generated? Well, I didn't know that. In that case, a longer token is not necessary. 

I thought the study admin should (arbitrarily) decide it.
(for example, https://heartsteps.net/dashboard/1/create )

If the study admin has to decide it without seeing others' tokens (even including people in other studies), I thought it would be difficult.

:)

Thank you for letting me know.


Junghwan
