### ISSUE TITLE
Daily step count goal that is visible on client if participant or cohort is configured for intervention

### ISSUE THREAD

**Issue by nickdotreid** [kpwhri/heartsteps#208]
Acceptance Criteria
- [x] Want simple UI to show daily step goal for participant
- [x] Need database table for step goal per participant per day
- [x] Pull daily step goal from database table
- [x] Display daily step goal on frontend
- [x] Implement update function to consistently update daily step goal in DSG component

**Comment by nickdotreid** [comment]
@rahul-dcosta Let's chat about databases and celery tasks

**Comment by nickdotreid** [comment]
We want to include 10 day sliding window to generate daily step-count goals

**Comment by rahul-dcosta** [comment]
Update function implemented. This runs in the constructor of the DSG component. It fetches the last value in the DSG table. The logic behind this being that at any point, the last value in the DSG table should correspond to the current date, so when update runs, it should fetch today's step goal.

All tasks complete for now, might have to revisit later to solidify once next issue (sending data to backend) is complete.
