### ISSUE TITLE
Heartsteps not pulling weekly goal data from django causing rendering issues throughout app

### ISSUE THREAD

**Issue by patrick9958** [kpwhri/heartsteps#210]
When first opening the mobile app after force closing (hard refreshing the page with Ctrl+R will replicate the bug), the weekly goal is rendered as "Weekly Goal: ". This is because the weeklyGoal class variable in DashboardPage is undefined upon first loading the Dashboard. This also means that the weekly goal pie graph renders incorrectly.

If you change the weekly goal in settings, it renders properly on the dashboard again.

**Comment by nickdotreid** [comment]
Good catch!

**Comment by klasnja** [comment]
Ha! I didn't even notice that one can change the goal in settings. And I've been using this thing for years!


Typed on a small device with fat fingers. Excuse the typos.

________________________________
From: Patrick Neggie ***@***.***>
Sent: Tuesday, June 8, 2021 3:58:14 PM
To: kpwhri/heartsteps ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kpwhri/heartsteps] Weekly goal circular progress bar doesn't update if you change your weekly goal in settings (#210)


If you change the weekly goal from 60 min to 120 min and you've done 30 min of exercise, the circular progress bar still renders 50% completion
