### ISSUE TITLE
Update daily step goals to backend

### ISSUE THREAD

**Issue by rahul-dcosta** [kpwhri/heartsteps#230]
Daily step goals table currently exists with user, daily step goal, date as fields. The Heartsteps frontend currently has the functionality to pull a value for a given date from the daily step goals database table and print it on the frontend. This ticket tracks creating functionality for the database table to be updated **daily** with the new step goal.

Acceptance criteria:
- [x] Implement function in daily_step_goals/tasks.py to perform nightly task
- [x] Navigate update method (celery or get data as needed)
- [x] Get data of last 10 steps
- [x] Calculate median of last 10 steps
- [x] Verify that application takes the median of last 10 steps
- [x] Test nightly update

**Comment by rahul-dcosta** [comment]
Need to make considerations about what to do with step goals for later than 10 days ago (aka the values that will eventually not be on the table of the row size 10). There are three options:
- Create a sliding window where the last 10 values will be considered in calculations. This maintains step goal data for every day in the history of the user. (best option)
- Delete old values
- Create another table to store old values

**Comment by klasnja** [comment]
Rahul,

I am confused. Why would the backend database table only store the last 10
days of goals? On the backend, we want to save all the goals that have been
set for a participant over the course of the study. Clearly, the current
day will be what’s displayed to the user, but for us to do the analyses of
goal attainment, we need to know every goal that was set for a person over
the duration of their participation.

I am wondering if you got confused between how the goal is set—which, for
the NLM study is based on the last ten days of step counts for a person—and
that we want to keep 10 days of goals. The main database table that’s
storing goals should just record the goal for each user for each day. We
want the complete record of all goals for everyone.

Thanks,
Pedja

**Comment by rahul-dcosta** [comment]
Hi Pedja,

So sorry for the confusion. I completely agree with the method of storing
the step goal data you have outlined. I was just listing out all the
possible options (including naive ones) just for my own purposes. I have
already begun implementing this in the direction you have outlined.

**Comment by rahul-dcosta** [comment]
Criteria fulfilled. Closing this issue and moving towards the next step here - importing .csv files with multipliers and applying to that day's step goals using the existing calculation for step goals (median of the last 10 days of steps).
