### ISSUE TITLE
OneSignal bug causes 5 minute notification rendering delay inside notification center

### ISSUE THREAD

**Issue by patrick9958** [kpwhri/heartsteps#235]
**5-6 minute delays for notifications to appear in the notification center because of OneSignal.**

Either we need to move away from OneSignal or figure out a way around this problem. To reproduce, log into a heartsteps account on the development server and send yourself a test notification. You should notice a 5 minute delay.

Notifications render within 5 seconds when testing in a local environment but lag in a real environment.

**Comment by nickdotreid** [comment]
A timeout of 5 minutes is configured in the [one_signal_received task](https://github.com/kpwhri/heartsteps/blob/master/server/push_messages/tasks.py#L19-L23) and [after a notification is sent](https://github.com/kpwhri/heartsteps/blob/master/server/push_messages/services.py#L99-L104)

The problems are is that this 5 minute delay is defined in two places, it should only live in a single place, so it can easily be changed.

We decided to change this to 30 seconds to resolve this issue.
