### ISSUE TITLE
FeatureFlag with "str.split" instead "str.includes"

### ISSUE THREAD

**Issue by jup014** [kpwhri/heartsteps#247]
I guess it is a temporary implementation, but the current implementation of FeatureFlagService.hasFlag() uses **str.includes()**:

https://github.com/kpwhri/heartsteps/blob/master/client/src/heartsteps/feature-flags/feature-flags.service.ts#L46

**.includes()** searches ***any*** matching substring. Thus, if the user has "notification" flag, **this.featureFlagService.hasFlag('noti')** returns **True**.

I guess it should be replaced with **str.split(',')** and the exact matching at some point. (not necessarily right now)

If it is the intended use, we might separate out the pattern matching like...

* FeatureFlagService.hasFlag(flagName:str)
* FeatureFlagService.hasFlagRE(flagNameRE:str)

But I guess it is not the case...

Thank you!

**Comment by patrick9958** [comment]
Already fixed this in a previous commit
