### ISSUE TITLE
Get weather from User Zip code

### ISSUE THREAD

**Issue by rahul-dcosta** [kpwhri/heartsteps#309]
Getting weather in user's location based on zip code.

Requirements:
- [x] Create dashboard form in dev/front to add zip code
- [x] Get location from all 5 digits
- [x] Update Place object with new coordinates

Full requirements not set yet.

**Comment by jup014** [comment]
If you set the Place object correctly, weather fetch will be done well. Don't worry about weather itself.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: rahul-dcosta ***@***.***>
Sent: Thursday, February 10, 2022 4:24:06 PM
To: kpwhri/heartsteps ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kpwhri/heartsteps] Get weather from User Zip code (Issue #309)


Getting weather in user's location based on zip code.

Requirements:

  *    Create dashboard form in dev/front to add zip code
  *    Get location from all 5 digits
  *    Get location from first 3 digits
  *    Get weather from location

Full requirements not set yet.

**Comment by jup014** [comment]
Done
