### ISSUE TITLE
Change daily EMA's title

### ISSUE THREAD

**Issue by jup014** [kpwhri/heartsteps#325]
- [x] Change the daily EMA's title from "How was your day?" to "Time to think and prepare for tomorrow's activity."
- [x] share the screenshots of iOS and Android

**Comment by patrick9958** [comment]
might be too long for a notification banner

**Comment by jup014** [comment]
The longer title doesn't overflow in either platform. I'll go with the longer title, as proposed previously by Eric. I'm open to either choice. We're discussing it on Slack.
