### ISSUE TITLE
Walking suggestion EMA Survey

### ISSUE THREAD

**Issue by klasnja** [kpwhri/heartsteps#89]
This ticket is based on this [google document about EMA questions.](https://docs.google.com/document/d/1Yy3Fz2gsjOgGhaSFHGkfeKGN7TKt19OjcTO0uVGXCTs/edit)

Participants will be randomized to receive a survey at a walking suggestion decision time, if they are configured to receive these surveys.

**Acceptance Criteria**
- [x] Participant can be configured to receive walking suggestion surveys.
- [ ] At walking suggestion time, participant is randomized to receive a walking suggestion survey, and the randomization decision is recorded.
- [ ] Participant's walking suggestion survey randomization can be configured individually, or uses probability set as environment variable.
- [x] Survey includes questions created for walking suggestion survey, and is sent as push message to participant.

**Comment by nickdotreid** [comment]
We are going to implement the logic to actually send notifications in a different ticket
